//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5WebApp.MovieService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieService.lProjectService")]
    public interface lProjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/sendMail", ReplyAction="http://tempuri.org/lProjectService/sendMailResponse")]
        string sendMail(string to, string details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/sendMail", ReplyAction="http://tempuri.org/lProjectService/sendMailResponse")]
        System.Threading.Tasks.Task<string> sendMailAsync(string to, string details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/TheatreList", ReplyAction="http://tempuri.org/lProjectService/TheatreListResponse")]
        string[] TheatreList(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/TheatreList", ReplyAction="http://tempuri.org/lProjectService/TheatreListResponse")]
        System.Threading.Tasks.Task<string[]> TheatreListAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/GetShowTimings", ReplyAction="http://tempuri.org/lProjectService/GetShowTimingsResponse")]
        string[] GetShowTimings(string filmname, string filmID, string cinemaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lProjectService/GetShowTimings", ReplyAction="http://tempuri.org/lProjectService/GetShowTimingsResponse")]
        System.Threading.Tasks.Task<string[]> GetShowTimingsAsync(string filmname, string filmID, string cinemaName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lProjectServiceChannel : Project5WebApp.MovieService.lProjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lProjectServiceClient : System.ServiceModel.ClientBase<Project5WebApp.MovieService.lProjectService>, Project5WebApp.MovieService.lProjectService {
        
        public lProjectServiceClient() {
        }
        
        public lProjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lProjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lProjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lProjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendMail(string to, string details) {
            return base.Channel.sendMail(to, details);
        }
        
        public System.Threading.Tasks.Task<string> sendMailAsync(string to, string details) {
            return base.Channel.sendMailAsync(to, details);
        }
        
        public string[] TheatreList(string name) {
            return base.Channel.TheatreList(name);
        }
        
        public System.Threading.Tasks.Task<string[]> TheatreListAsync(string name) {
            return base.Channel.TheatreListAsync(name);
        }
        
        public string[] GetShowTimings(string filmname, string filmID, string cinemaName) {
            return base.Channel.GetShowTimings(filmname, filmID, cinemaName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetShowTimingsAsync(string filmname, string filmID, string cinemaName) {
            return base.Channel.GetShowTimingsAsync(filmname, filmID, cinemaName);
        }
    }
}
